name: Crafu'r data diweddaraf

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5,25,45 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://www.s4c.cymru/df/programme_feed_by_category?lang=c&id=1 | jq . > ffeithiolcelf.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Data diweddaraf: ${timestamp}" || exit 0
        git push
